### ISSUE TITLE
关于Lorettarep

### ISSUE THREAD

**Issue by shengtan123** [yifanycc/loretta#1]
你好，我看了loretta/tuners/loretta_rep.py文件，其中在构建lorettarepmodel替换相应的module时，我好像只发现了其添加的是普通的lora模块，并没有论文中提到的TT分解。不知是否是我的理解问题，请指正！

**Comment by yifanycc** [comment]
你好，loretta_rep.py里面是在140行和155行添加的TT分解的lora模块。你看Linear和MergedLinear里面用的wrapped_linear_layers就是采用TT-format表示的线型层。Linear和MergedLinear的区别在于，MergedLinear应用于deberta这类qkv使用一个变量初始化的model，Linear适用于正常的query, key, value分别初始化的model。8bit的layer （Linear8bitLt）暂时还没有implement所有没有TT分解。如果有疑问可以跟我follow-up， 感谢！
